# Generated by Django 5.2.11 on 2026-02-19 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo de datos (QVD, CSV, XLSX)', upload_to='reports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='Extensión del archivo (csv, qvd, xlsx)', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_data', models.JSONField(blank=True, help_text='JSON procesado listo para Chart.js', null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('columns_detected', models.JSONField(blank=True, help_text='Lista de columnas detectadas con tipo', null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Informe',
                'verbose_name_plural': 'Archivos de Informes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
