# Generated by Django 5.2.11 on 2026-02-19 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_datamodelconfig_datasource_reportsheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsheet',
            name='data_model',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='layout_json',
            field=models.JSONField(default=list, help_text='Lista de configuraciones de gráficos'),
        ),
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('engine', models.CharField(choices=[('sqlserver', 'SQL Server'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite')], default='sqlserver', max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=1433)),
                ('database', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoadScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query_text', models.TextField(help_text='Query SQL a ejecutar (SELECT, JOINs, etc.)')),
                ('last_row_count', models.PositiveIntegerField(default=0)),
                ('last_column_count', models.PositiveIntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='reports.dbconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='load_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='reports.loadscript'),
        ),
        migrations.DeleteModel(
            name='DataModelConfig',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
