# Generated by Django 5.2.11 on 2026-02-19 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_reportsheet_data_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsheet',
            name='load_script',
        ),
        migrations.AlterModelOptions(
            name='reportsheet',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='reportsheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportsheet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportsheet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reportsheet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='engine',
            field=models.CharField(choices=[('sqlserver', 'SQL Server'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], default='sqlserver', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='layout_json',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ReportApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AppLoadScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Extracción Clientes Sage', max_length=100)),
                ('query_text', models.TextField(help_text='SELECT query to execute')),
                ('order', models.IntegerField(default=0, help_text='Execution order')),
                ('last_row_count', models.PositiveIntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='load_scripts', to='reports.dbconnection')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='reports.reportapp')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='reports.reportapp'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoadScript',
        ),
    ]
