# Generated by Django 5.2.11 on 2026-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='readable_password',
            field=models.CharField(blank=True, default='', help_text='Contraseña en texto plano para consulta del Admin (Intranet).', max_length=128, verbose_name='Contraseña visible'),
        ),
    ]
